### ISSUE TITLE
Request: cross-publish on Open VSX

### ISSUE THREAD

**Issue by awebeer256** [whubsch/vscode-mapcss-syntax#1]
[VSCodium](https://github.com/VSCodium/vscodium) and other VSCode forks are not allowed to use the Microsoft extension marketplace, so they use [Open VSX](https://open-vsx.org/) instead. Would you please publish this extension there as well, so those users (including me!) can use it without manually downloading the `.vsix` file? More background [here](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace).

**Comment by whubsch** [comment]
Done [here](https://open-vsx.org/extension/whammo/mapcss-syntax). Will close this issue when my claim on the `whammo` namespace is complete (EclipseFdn/open-vsx.org#2150)
